### ISSUE TITLE
I'm not familiar with using java but I can't run the program

### ISSUE THREAD

**Issue by lininjim2** [TheMontezuma/NVC#2]
I get this error 
**Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 4 more
Finished
Press any key to continue . . .**

Windows 11, running java version "22" 2024-03-19
Java(TM) SE Runtime Environment (build 22+36-2370)
Java HotSpot(TM) 64-Bit Server VM (build 22+36-2370, mixed mode, sharing)

I appreciate this is _my_ lack of knowledge but I hope some kind person might help. Thank you.

**Comment by lininjim2** [comment]
And running it as a GUI app after installing Java works perfectly. Thank you for the help on FB.
